//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenWeatherApiTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenWeatherApiTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.67:139.65:Asia/Tokyo.
        /// </summary>
        internal static string brisbane {
            get {
                return ResourceManager.GetString("brisbane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41.87:-87.62:America/Chicago.
        /// </summary>
        internal static string chicago {
            get {
                return ResourceManager.GetString("chicago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 51.50:0.12:Europe/London.
        /// </summary>
        internal static string london {
            get {
                return ResourceManager.GetString("london", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.85:2.35:Europe/Paris.
        /// </summary>
        internal static string paris {
            get {
                return ResourceManager.GetString("paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -27.46:153.02:Australia/Brisbane.
        /// </summary>
        internal static string tokyo {
            get {
                return ResourceManager.GetString("tokyo", resourceCulture);
            }
        }
    }
}
